import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(__dirname, '..');
const source = readFileSync(join(root, 'app/markets/page.tsx'), 'utf8');
const cardSource = readFileSync(join(root, 'components/markets/MarketListCard.tsx'), 'utf8');
const addFormSource = readFileSync(join(root, 'components/markets/AddMarketForm.tsx'), 'utf8');
const editFormSource = readFileSync(join(root, 'components/markets/EditMarketForm.tsx'), 'utf8');

assert.match(source, /buildMarketListGroups\(allMarkets, now\)/);
assert.match(source, /label: '進行中'/);
assert.match(source, /label: '待準備'/);
assert.match(source, /label: '已結束'/);
assert.match(source, /查看已取消市集/);
assert.match(source, /<Tabs/);
assert.match(source, /MARKET_LIST_RETURN_STATE_KEY/);
assert.match(source, /preparationFilter: MarketPreparationFilter/);
assert.match(source, /aria-label="待準備報名進度篩選"/);
assert.match(source, /label: '等待錄取'/);
assert.match(source, /label: '待繳費'/);
assert.match(source, /item\.preparationAttention === preparationFilter/);
assert.match(source, /scrollY: window\.scrollY/);
assert.match(source, /<MarketListCard/);
assert.match(cardSource, /\{item\.statusLabel\}/);
assert.match(cardSource, /text-\[13px\] font-semibold ring-1/);
assert.match(cardSource, /item\.market\.status === 'accepted'/);
assert.match(cardSource, /item\.market\.status === 'paid'/);
assert.match(cardSource, /\{item\.dateRangeLabel\}/);
assert.match(cardSource, /尚未設定報到與營業時間/);
assert.match(cardSource, /預設時段，請確認/);
assert.match(cardSource, /預估支出/);
assert.match(cardSource, /保證金/);
assert.match(cardSource, /financeParts\.length > 0/);
assert.match(cardSource, /equipment\.status === 'provided'/);
assert.doesNotMatch(cardSource, />設備</);
assert.match(cardSource, /查看主辦／場地備註/);
assert.match(cardSource, /<StickyNote/);
assert.match(cardSource, /<AppDialog/);
assert.match(cardSource, /aria-label=\{`開啟「\$\{item\.market\.name\}」詳情`\}/);
assert.match(cardSource, /absolute inset-0 z-0 rounded-card/);
assert.match(cardSource, /pointer-events-none relative z-10/);
assert.doesNotMatch(cardSource, /<Store/);
assert.doesNotMatch(cardSource, /查看準備/);
assert.doesNotMatch(cardSource, /getMarketListActionLabel/);
assert.doesNotMatch(source, />操作</);
assert.match(cardSource, /completion\.totalRevenue/);
assert.match(cardSource, /估計淨利/);
assert.match(cardSource, /completion\.totalDeals/);
assert.match(cardSource, /!isStaff && completion\.totalRevenue !== null/);
assert.match(addFormSource, /checkInTime: ''/);
assert.match(addFormSource, /operatingStartTime: ''/);
assert.match(addFormSource, /checkInTime: formData\.checkInTime \|\| undefined/);
assert.match(editFormSource, /checkInTime: market\.checkInTime \|\| ''/);
assert.doesNotMatch(source, /formatDateKey\(item\.displayDate\)/);
assert.match(source, /dynamic\(/);
assert.match(source, /isFormOpen &&/);
assert.doesNotMatch(source, /useMarketStatsBatch|<MarketCard/);
assert.doesNotMatch(source, /getFilteredMarkets|TabType|SORT_ASCENDING_TABS/);

console.log('PASS work-stage market list UI');
